### ISSUE TITLE
Missing Files Error (clang: error: no such file or directory:)

### ISSUE THREAD

**Issue by adromil** [PayMaya/PayMaya-iOS-SDK#1]
Encountered errors while compiling the Example App (PayMayaSDK-Example).
Error found as follows:
clang: error: no such file or directory:
'Pods/PayMayaSDK/Pod/Classes/PayMayaSDK.m'
'Pods/PayMayaSDK/Pod/Classes/Backend/NSObject+KVCParsing.m'
'Pods/PayMayaSDK/Pod/Classes/Models/PMSDKAddress.m'
![screen shot 2016-08-16 at 1 40 22 pm](https://cloud.githubusercontent.com/assets/1217347/17689139/09f28bf6-63b8-11e6-9475-4dde8792f473.png)
![screen shot 2016-08-16 at 1 48 53 pm](https://cloud.githubusercontent.com/assets/1217347/17689176/3b801814-63b8-11e6-8cf7-05b46d3f3265.png)

**Comment by ebcayabyab** [comment]
Fixed in version 0.3.4
