### ISSUE TITLE
Undeclared type PMSDKCheckoutRedirectURL

### ISSUE THREAD

**Issue by adromil** [PayMaya/PayMaya-iOS-SDK#2]
Unable to instantiate `PMSDKCheckoutRedirectURL` type and `PMSDKCheckoutInformation` type has no member `redirectUrl` (

> `PMSDKCheckoutInformation.redirectUrl`

 is also an issue) tried on both **`Objective-C`** and **`Swift 2.0`**

**Comment by ebcayabyab** [comment]
Fixed in version 0.3.4
